export const APOIA_SE_URL = 'https://apoia.se/soujunior'
export const DISCORD_URL = 'https://discord.gg/FkBcf3vdQZ'
export const WHATSAPP_URL = 'https://chat.whatsapp.com/JJzCMlqMKlw1YOhOk7QB3W'
export const GITHUB_URL = 'https://github.com/SouJunior'
export const SITE_URL = 'https://soujunior.tech'
